services:
  nbfirefly_mysql:
    image: mysql:8.0.30
    volumes:
      - ${HOST_DB_PATH}:/var/lib/mysql/:rw
    environment:
      - MYSQL_DATABASE=nbfirefly
      - MYSQL_ROOT_PASSWORD=YES
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp


  nb_tt_mac:
      build:
        context: .
        dockerfile: Dockerfile.M1
        platforms:
          - linux/amd64
          - linux/arm64
      image: nb_tensortrade
      container_name: nb_tensortrade

      environment:
        TZ: "America/new_york"
      ports:
        - "8282:8282"
      # Define OS-specific paths in .env.mac or .env.ubuntu and run docker-compose using --env-file accordingly
      volumes:
        - ./.docker/.ipython:/root/.ipython:cached
        - ${HOST_NOTEBOOK_PATH}:/home/jupyter/notebook:rw
        - ${HOST_PROJECTS_PATH}:/home/jupyter/projects:rw
        - ${HOST_WORKDIR_PATH}:/workdir:rw
      depends_on:
        #- vpn
        - nbfirefly_mysql
